distributors = {
    # Forventet i filen : Distributør kode som Wolf forventer
    "Søderberg og Partners Wealth Management AS": "SP",
    "Sparebank1 Nord-Norge": "SB1SNN",
    "Sparebank 1 Nord-Norge" : "SB1SNN",
    "Søderberg og Partners": "SP",
    "kron": "Kron AS",
    "SPAREBANK 1 SR": "SpareBank 1 SR-Bank",
    "Sb1SR": "SpareBank 1 SR-Bank",
    "Sb1Ostl": "SB1Ø",
    "Sparebank 1 Østlandet" : "SB1Ø",
    "SÃ¶derberg & Partners Wealth Management AS": "SP",
    "Pareto Securities" : "Pareto Securities AS",
    "Huddlestock Investor Services" : "HI",
    "FONDFINANS" : "Fondsfinans",
    "Sparebank 1 Nordmøre" : "SB1Nm",
    "Sparebank 1 SMN" : "SB1SMN",
    "SB1Sorost" : "SB1SØN",
    "SpareBank 1 Sørøst-Norge" : "SB1SØN",
    "Söerberg & Partners Wealth Management AS" : "SP",
    "Söderberg & Partners Wealth Management AS" : "SP",
    "Lyberg & Partnere" : "LYBERG",
    "SpareBank 1 Østfold Akershus" : "SB1SØA",
    "Alfred Berg" : "AB",
    "Arctic Fund Management AS" : "AFM",
    "Fondsfinans Kapitalforvaltning AS" : "Fondsfinans",
    "Nordea Direct Bank AS" : "GB",
    "Fronteer Solutions" : "HARVEST",
    "Heimdal Forvaltning" : "HF",
    "Holberg Fondene" : "HFF",
    "Huddlestock Investor Services AS" : "HI",
    "Landkreditt Bank" : "LKB",
    "Nordea NO" : "NDA",
    "Netfonds Bank" : "NF",
    "ODIN Forvaltning" : "ODIN",
    "Pareto Wealth Management AS" : "Pareto Wealth Mgmt",
    "Pareto" : "ParetoAM",
    "SpareBank 1 Søre Sunnmøre" : "SB1SøreSunnmøre",
    "Sparebanken Møre" : "SBM",
    "Sparebank1 Verdipapirservice" : "SB1VPS",
    "Sparebanken Vest" : "SPV",
    "C WorldWide Asset Management" : "CWW",
    "Fondsforvaltning AS" : "PLUSS",
    "Forte Fondsforvaltning" : "FORTE",
    "SpareBank 1 Gudbrandsdal" : "SB1G",
    "SpareBank 1 Hallingdal Valdres" : "SB1HV",
    "SpareBank 1 Lom og Skjåk" : "SB1LS",
    "SpareBank 1 Modum" : "SB1MOD",
    "SpareBank 1 Nordvest" : "SB1NV",
    "SpareBank 1 Ringerike Hadeland" : "SB1RH",
    "SpareBank 1 Telemark" : "SB1T",
    "FIRST Fondene AS" : "FIRSTASK",
    "Invento Kapitalforvaltning" : "INV",
    "Sparebank 1 Sogn og Fjordane" : "SB1SF",
    "Sandnes Sparebank" : "SandnesSparebank",
    "Sparebanken Sør" : "SparebankenSør",
    "Skudenes & Aakra Sparebank" : "Skudenes",
    "Finansco" : "FIN",
    "Jernbanepersonalets Sparebank" : "Jernbanepers SB",
    "Fana Sparebank" : "Fana SB",
    "Clarkson Platou Securities" : "CPS",
    "Flekkefjord Sparebank" : "FSB",
    "Sparebank 1 Buskerud og Vestfold" : "SB1BV",
    "Sissener AS" : "SIS",
    "Harvest Funds AS" : "HARVESTF",
    "Haugesund Sparebank" : "HGSB",
    "Norse Forvaltning" : "Norse",
    "Rørosbanken" : "RORBANK",
    "Kraft Finans" : "KRAFT",
    "Pensum Asset Management" : "PEN",
    "Njord Kapitalforvaltning" : "NK",
    "Industrifinans Kapitalforvaltning" : "Industri",
    "SPAREBANK 1 KAPITALFORVALTNING AS" : "SB1K",
    "Borea Asset Management AS" : "BAM",
    "Jæren Sparebank" : "JÆR",
    "Orkla Sparebank" : "ORCLA",
    "Fair Investments" : "FAIR",
    "FRAM Fondene" : "FRAM",
    "Vertu Kapitalforvaltning" : "VK",
    "Sparebank 1 Nord-Norde" : "SB1NN",
    "KLP Kapitalforvaltning" : "KLP",
    "Toten Sparebank" : "TOT",
    "Sparebanken Øst" : "SPØ",
    "Din Bank" : "DinBank",
    "Lillesands Sparebank" : "Lillesands SB",
    "Nidaros Sparebank" : "Nidaros SB",
    "Obos Banken" : "OBOS",
    "Omega Finansrådgivning" : "OMEGA Finans",
    "Romsdalsbanken" : "Romsdalbanken",
    "Søgne og Greipstad Sparebank" : "Søgne og Greipstad SB",
    "Ørskog sparebank" : "Ørskog SB",
    "Pareto Asset Management" : "PAM",
    "Romerike sparebank" : "ROM SB1",
    "Stack By Me AS" : "STACK",
    "Sparebanken 68 Grader Nord" : "SB68NORD",
    "Heimdal Forvaltning AS" : "HF",
    "Sb1Helg" : "Sparebank 1 Helgeland",
    "Alfred Berg Kapitalforvaltning" : "AB",
    "Söderberg og Partners WM": "SP"

}
NTO_distributors = {
    "Sparebank 1 SR" : "Sparebank 1 SR-Bank",
    "NORNEFDS" : "NORNE",
    "Sparebank 1 Sør-Norge" : "Sparebank 1 SR-Bank",
    "SPARBSMN" : "Sparebank 1 SMN",
    "SPARBK_1" : "Sparebank 1 SR-Bank"


}

tax_key = ["skattedata", "skatedata", "kateopplysninger", "Skatteopplysninger (Utbytte angis pr.  ISIN)", "skattASK"]
